version: '3.8'

services:
  rapids-pycaret-gpu:
    # ビルド設定（BuildKit有効化で高速化）
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
      cache_from:
        - nvcr.io/nvidia/rapidsai/base:25.06-cuda12.8-py3.11

    container_name: rapids_pycaret_notebook

    # 環境変数
    environment:
      # GPU設定
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - RAPIDS_NO_INITIALIZE=1
      # Jupyter設定
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=
      # 日本語設定
      - LANG=ja_JP.UTF-8
      - LC_ALL=ja_JP.UTF-8
      # CUDA設定
      - CUDA_VISIBLE_DEVICES=0
      # メモリ管理
      - CUPY_CACHE_DIR=/tmp/cupy_cache
      - NUMBA_CACHE_DIR=/tmp/numba_cache

    # ポート設定
    ports:
      - "8888:8888"

    # ボリューム設定
    volumes:
      # 作業ディレクトリ（HOST_WORK_DIRがあれば優先。無ければ相対パス）
      - ${HOST_WORK_DIR:-../../work}:/home/rapids/work:rw
      # キャッシュディレクトリ
      - ./cache/cupy:/tmp/cupy_cache:rw
      - ./cache/numba:/tmp/numba_cache:rw
      # Jupyterの設定（永続化）- 一時的にコメントアウト
      # - ./jupyter_config:/home/rapids/.jupyter:rw

    # GPU設定
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    # 共有メモリサイズ
    shm_size: '64gb'

    # 再起動ポリシー
    restart: unless-stopped

    # ヘルスチェック
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    # ネットワーク設定
    networks:
      - rapids-network

# ネットワーク定義
networks:
  rapids-network:
    driver: bridge

# ボリューム定義
volumes:
  work_data:
    driver: local
  jupyter_config:
    driver: local
